sudo ./addceuuser.sh Amodei_Ellen
sudo ./addceuuser.sh Baldwin_Alexander
sudo ./addceuuser.sh Bangari_Adarsh_Gurappa
sudo ./addceuuser.sh Berki_Tamas
sudo ./addceuuser.sh Boda_Imre
sudo ./addceuuser.sh Bokonyi_Gabor
sudo ./addceuuser.sh Burghard_Tamas
sudo ./addceuuser.sh Chytil_Mario
sudo ./addceuuser.sh Dalnoki_Gabor
sudo ./addceuuser.sh Demeter_Melinda
sudo ./addceuuser.sh Domokos_Barna
sudo ./addceuuser.sh Duronelly_Peter
sudo ./addceuuser.sh Elhence_Geeta
sudo ./addceuuser.sh Gesheva_Nadezhda
sudo ./addceuuser.sh Gomes_Nuno
sudo ./addceuuser.sh Haider_Ali
sudo ./addceuuser.sh Illes_Gabor
sudo ./addceuuser.sh Kelemen_Andras
sudo ./addceuuser.sh Kinizsi_Gergely
sudo ./addceuuser.sh Koncz_Tamas
sudo ./addceuuser.sh Kozula_Adam
sudo ./addceuuser.sh Kratzer_William
sudo ./addceuuser.sh McGrew_Jacob
sudo ./addceuuser.sh Mirhossein_Seyed_Reza
sudo ./addceuuser.sh Nand_Gaurav
sudo ./addceuuser.sh Niranjan_Nikitha
sudo ./addceuuser.sh Papp_Roland
sudo ./addceuuser.sh Pasztor_Aurel
sudo ./addceuuser.sh Paziczki_Peter
sudo ./addceuuser.sh Radics_Gabor_Balint
sudo ./addceuuser.sh Szamohval_Monika_Mira
sudo ./addceuuser.sh Szilagyi_Laszlo_Janos
sudo ./addceuuser.sh Tagai_Lilla
sudo ./addceuuser.sh Tumaliuan_Faye_Beatriz
sudo ./addceuuser.sh Verkmann_Gabor
sudo ./addceuuser.sh Weidlich_David_Laszlo
sudo ./addceuuser.sh Yetkin_Cagdas
sudo ./addceuuser.sh Zankay_Balazs_Peter
